[package]
name = "mettle"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib 	 = { version = "5.5.1" }
rapier3d = { version = "0.26.1", features = ["simd-stable", "debug-render"] }
anyhow   = { version = "1.0"   }
rand     = { version = "0.9.2" }

[profile.dev.package.rapier3d]
opt-level = 3