[package]
name 	= "engine_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
syn 	   = { version = "2.0" }
serde      = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[lib]
proc-macro = true